// Generated by CoffeeScript 1.6.3
(function() {
  var clickListener, insertLink;

  insertLink = function($listHeaderQuickIcons) {
    var $link;
    $link = $("<div class='expand-collapse-all-cards icon-list' title='Expand or collapse all cards in this list'></div>");
    $link.on("click", clickListener);
    return $listHeaderQuickIcons.prepend($link);
  };

  clickListener = function(event) {
    var firstCard, listId, shouldOpen;
    listId = $(event.target).closest(".board-list").attr("data-id");
    firstCard = Cards.findOne({
      listId: listId
    }, {
      sort: {
        position: 1
      }
    });
    if (!firstCard) {
      return;
    }
    shouldOpen = !Session.get(firstCard.htmlId() + "-is-open");
    return Cards.find({
      listId: listId
    }).forEach(function(card) {
      return Session.set(card.htmlId() + "-is-open", shouldOpen);
    });
  };

  Template.listHeader.rendered = _.compose(function() {
    return insertLink($(this.find(".board-list-header .quick-icons")));
  }, Template.listHeader.rendered);

  Meteor.startup(function() {
    return insertLink($(".board-list-header .quick-icons"));
  });

}).call(this);

/*
//@ sourceMappingURL=plugin.map
*/
